/*
Deployment script for casino_2

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

drop database if exists [casino_2]
go

create database [casino_2]


GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "casino_2"
:setvar DefaultFilePrefix "casino_2"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Creating Table [dbo].[cardspkg]...';


GO
CREATE TABLE [dbo].[cardspkg] (
    [id]          INT NULL,
    [cardvalue]   INT NULL,
    [cardsymbol]  INT NULL,
    [isavailable] BIT NULL
);


GO
PRINT N'Creating Table [dbo].[configuration]...';


GO
CREATE TABLE [dbo].[configuration] (
    [id]          INT           IDENTITY (1, 1) NOT NULL,
    [description] VARCHAR (MAX) NULL,
    [value]       INT           NULL,
    CONSTRAINT [PK_configuration] PRIMARY KEY CLUSTERED ([id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Countries]...';


GO
CREATE TABLE [dbo].[Countries] (
    [CountryId]   INT          NOT NULL,
    [CountryName] VARCHAR (30) NULL,
    CONSTRAINT [PK_Countries] PRIMARY KEY CLUSTERED ([CountryId] ASC)
);


GO
PRINT N'Creating Table [dbo].[Games]...';


GO
CREATE TABLE [dbo].[Games] (
    [GameId]   INT          NOT NULL,
    [GameName] VARCHAR (20) NULL,
    CONSTRAINT [PK_Games] PRIMARY KEY CLUSTERED ([GameId] ASC)
);


GO
PRINT N'Creating Table [dbo].[Gender]...';


GO
CREATE TABLE [dbo].[Gender] (
    [GenderID]   INT         NOT NULL,
    [GenderName] VARCHAR (6) NULL,
    CONSTRAINT [PK_Gender] PRIMARY KEY CLUSTERED ([GenderID] ASC)
);


GO
PRINT N'Creating Table [dbo].[log]...';


GO
CREATE TABLE [dbo].[log] (
    [ProcedurName] VARCHAR (100) NOT NULL,
    [RunDate]      DATETIME      NOT NULL,
    CONSTRAINT [PK_log] PRIMARY KEY CLUSTERED ([ProcedurName] ASC, [RunDate] ASC)
);


GO
PRINT N'Creating Table [dbo].[MSSQL_TemporalHistoryFor_581577110]...';


GO
CREATE TABLE [dbo].[MSSQL_TemporalHistoryFor_581577110] (
    [UserNameID]          INT           NOT NULL,
    [UserName]            NVARCHAR (10) NOT NULL,
    [Password]            VARCHAR (20)  NOT NULL,
    [FirstName]           VARCHAR (20)  NULL,
    [LastName]            VARCHAR (20)  NULL,
    [Adress]              VARCHAR (100) NULL,
    [CountryId]           INT           NULL,
    [EMail]               VARCHAR (15)  NULL,
    [GenderID]            INT           NOT NULL,
    [BirthDate]           DATETIME2 (7) NOT NULL,
    [isblocked]           INT           NOT NULL,
    [CountFailedPassword] INT           NOT NULL,
    [ValidFrom]           DATETIME2 (7) NOT NULL,
    [ValidUntil]          DATETIME2 (7) NOT NULL
);


GO
PRINT N'Creating Index [dbo].[MSSQL_TemporalHistoryFor_581577110].[ix_MSSQL_TemporalHistoryFor_581577110]...';


GO
CREATE CLUSTERED INDEX [ix_MSSQL_TemporalHistoryFor_581577110]
    ON [dbo].[MSSQL_TemporalHistoryFor_581577110]([ValidUntil] ASC, [ValidFrom] ASC) WITH (DATA_COMPRESSION = PAGE);


GO
PRINT N'Creating Table [dbo].[MSSQL_TemporalHistoryFor_581577110_831D5114]...';


GO
CREATE TABLE [dbo].[MSSQL_TemporalHistoryFor_581577110_831D5114] (
    [UserNameID]          INT           NOT NULL,
    [UserName]            NVARCHAR (10) NOT NULL,
    [Password]            VARCHAR (20)  NOT NULL,
    [FirstName]           VARCHAR (20)  NULL,
    [LastName]            VARCHAR (20)  NULL,
    [Adress]              VARCHAR (100) NULL,
    [CountryId]           INT           NULL,
    [EMail]               VARCHAR (30)  NULL,
    [GenderID]            INT           NOT NULL,
    [BirthDate]           DATE          NULL,
    [isblocked]           INT           NOT NULL,
    [CountFailedPassword] INT           NOT NULL,
    [ValidFrom]           DATETIME2 (7) NOT NULL,
    [ValidUntil]          DATETIME2 (7) NOT NULL,
    [LoginIndicator]      INT           NOT NULL
);


GO
PRINT N'Creating Index [dbo].[MSSQL_TemporalHistoryFor_581577110_831D5114].[ix_MSSQL_TemporalHistoryFor_581577110_831D5114]...';


GO
CREATE CLUSTERED INDEX [ix_MSSQL_TemporalHistoryFor_581577110_831D5114]
    ON [dbo].[MSSQL_TemporalHistoryFor_581577110_831D5114]([ValidUntil] ASC, [ValidFrom] ASC) WITH (DATA_COMPRESSION = PAGE);


GO
PRINT N'Creating Table [dbo].[MSSQL_TemporalHistoryFor_581577110_F69B3273]...';


GO
CREATE TABLE [dbo].[MSSQL_TemporalHistoryFor_581577110_F69B3273] (
    [UserNameID]          INT           NOT NULL,
    [UserName]            NVARCHAR (10) NOT NULL,
    [Password]            VARCHAR (20)  NOT NULL,
    [FirstName]           VARCHAR (20)  NULL,
    [LastName]            VARCHAR (20)  NULL,
    [Adress]              VARCHAR (100) NULL,
    [CountryId]           INT           NULL,
    [EMail]               VARCHAR (30)  NULL,
    [GenderID]            INT           NOT NULL,
    [BirthDate]           DATETIME2 (7) NOT NULL,
    [isblocked]           INT           NOT NULL,
    [CountFailedPassword] INT           NOT NULL,
    [ValidFrom]           DATETIME2 (7) NOT NULL,
    [ValidUntil]          DATETIME2 (7) NOT NULL
);


GO
PRINT N'Creating Index [dbo].[MSSQL_TemporalHistoryFor_581577110_F69B3273].[ix_MSSQL_TemporalHistoryFor_581577110_F69B3273]...';


GO
CREATE CLUSTERED INDEX [ix_MSSQL_TemporalHistoryFor_581577110_F69B3273]
    ON [dbo].[MSSQL_TemporalHistoryFor_581577110_F69B3273]([ValidUntil] ASC, [ValidFrom] ASC) WITH (DATA_COMPRESSION = PAGE);


GO
PRINT N'Creating Table [dbo].[MSSQL_TemporalHistoryFor_725577623]...';


GO
CREATE TABLE [dbo].[MSSQL_TemporalHistoryFor_725577623] (
    [UserID]     INT           NOT NULL,
    [Password]   VARCHAR (8)   NOT NULL,
    [ValidFrom]  DATETIME2 (7) NOT NULL,
    [ValidUntil] DATETIME2 (7) NOT NULL
);


GO
PRINT N'Creating Index [dbo].[MSSQL_TemporalHistoryFor_725577623].[ix_MSSQL_TemporalHistoryFor_725577623]...';


GO
CREATE CLUSTERED INDEX [ix_MSSQL_TemporalHistoryFor_725577623]
    ON [dbo].[MSSQL_TemporalHistoryFor_725577623]([ValidUntil] ASC, [ValidFrom] ASC) WITH (DATA_COMPRESSION = PAGE);


GO
PRINT N'Creating Table [dbo].[Passwords]...';


GO
CREATE TABLE [dbo].[Passwords] (
    [UserID]     INT                                         NOT NULL,
    [Password]   VARCHAR (8)                                 NOT NULL,
    [ValidFrom]  DATETIME2 (7) GENERATED ALWAYS AS ROW START NOT NULL,
    [ValidUntil] DATETIME2 (7) GENERATED ALWAYS AS ROW END   NOT NULL,
    PRIMARY KEY CLUSTERED ([UserID] ASC),
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidUntil])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[dbo].[MSSQL_TemporalHistoryFor_725577623], DATA_CONSISTENCY_CHECK=ON));


GO
PRINT N'Creating Table [dbo].[Players]...';


GO
CREATE TABLE [dbo].[Players] (
    [UserNameID]          INT                                         IDENTITY (1, 1) NOT NULL,
    [UserName]            NVARCHAR (10)                               NOT NULL,
    [Password]            VARCHAR (20)                                NOT NULL,
    [FirstName]           VARCHAR (20)                                NULL,
    [LastName]            VARCHAR (20)                                NULL,
    [Adress]              VARCHAR (100)                               NULL,
    [CountryId]           INT                                         NULL,
    [EMail]               VARCHAR (30)                                NULL,
    [GenderID]            INT                                         NOT NULL,
    [BirthDate]           DATE                                        NULL,
    [isblocked]           INT                                         NOT NULL,
    [CountFailedPassword] INT                                         NOT NULL,
    [ValidFrom]           DATETIME2 (7) GENERATED ALWAYS AS ROW START NOT NULL,
    [ValidUntil]          DATETIME2 (7) GENERATED ALWAYS AS ROW END   NOT NULL,
    [LoginIndicator]      INT                                         NOT NULL,
    PRIMARY KEY CLUSTERED ([UserNameID] ASC),
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidUntil])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[dbo].[MSSQL_TemporalHistoryFor_581577110_831D5114], DATA_CONSISTENCY_CHECK=ON));


GO
PRINT N'Creating Table [dbo].[tbl_slot]...';


GO
CREATE TABLE [dbo].[tbl_slot] (
    [symboles] VARCHAR (10) NULL
);


GO
PRINT N'Creating Table [dbo].[Transactions]...';


GO
CREATE TABLE [dbo].[Transactions] (
    [UserID]            INT      NOT NULL,
    [StartPlay]         DATETIME NOT NULL,
    [GameId]            INT      NULL,
    [Round]             INT      NULL,
    [TransactionTypeID] INT      NOT NULL,
    [Amount]            MONEY    NULL,
    [BankRoll]          MONEY    NULL,
    CONSTRAINT [PK_Transactions] PRIMARY KEY CLUSTERED ([UserID] ASC, [StartPlay] ASC, [TransactionTypeID] ASC)
);


GO
PRINT N'Creating Table [dbo].[TransactionType]...';


GO
CREATE TABLE [dbo].[TransactionType] (
    [TransactionTypeID] INT          IDENTITY (1, 1) NOT NULL,
    [TransactionType]   VARCHAR (10) NOT NULL,
    PRIMARY KEY CLUSTERED ([TransactionTypeID] ASC)
);


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Players]...';


GO
ALTER TABLE [dbo].[Players]
    ADD DEFAULT ((0)) FOR [isblocked];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Players]...';


GO
ALTER TABLE [dbo].[Players]
    ADD DEFAULT ((0)) FOR [CountFailedPassword];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Players]...';


GO
ALTER TABLE [dbo].[Players]
    ADD DEFAULT ((1)) FOR [LoginIndicator];


GO
PRINT N'Creating Foreign Key [dbo].[FK_Players_Countries]...';


GO
ALTER TABLE [dbo].[Players] WITH NOCHECK
    ADD CONSTRAINT [FK_Players_Countries] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Countries] ([CountryId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Players_Gender]...';


GO
ALTER TABLE [dbo].[Players] WITH NOCHECK
    ADD CONSTRAINT [FK_Players_Gender] FOREIGN KEY ([GenderID]) REFERENCES [dbo].[Gender] ([GenderID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Transactions_Games]...';


GO
ALTER TABLE [dbo].[Transactions] WITH NOCHECK
    ADD CONSTRAINT [FK_Transactions_Games] FOREIGN KEY ([GameId]) REFERENCES [dbo].[Games] ([GameId]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Transactions_Players]...';


GO
ALTER TABLE [dbo].[Transactions] WITH NOCHECK
    ADD CONSTRAINT [FK_Transactions_Players] FOREIGN KEY ([UserID]) REFERENCES [dbo].[Players] ([UserNameID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Transactions_TransactionType]...';


GO
ALTER TABLE [dbo].[Transactions] WITH NOCHECK
    ADD CONSTRAINT [FK_Transactions_TransactionType] FOREIGN KEY ([TransactionTypeID]) REFERENCES [dbo].[TransactionType] ([TransactionTypeID]);


GO
PRINT N'Creating View [dbo].[view_GETRANDVALUE]...';


GO
CREATE view view_GETRANDVALUE
AS
select rand() as value
GO
PRINT N'Creating View [dbo].[view_SLOTMACHINE]...';


GO
CREATE view view_SLOTMACHINE
as
	select top 1 * from tbl_slot order by NEWID()
GO
PRINT N'Creating View [dbo].[vv_GETRANDVALUE]...';


GO

CREATE view vv_GETRANDVALUE
AS
SELECT RAND() as value
GO
PRINT N'Creating Function [dbo].[fn_18_years_old]...';


GO
create function dbo.fn_18_years_old(@BirthDate date)
returns int
as
begin
declare @years_old int
	set @years_old = year(getdate()) - year(@BirthDate)

if month(getdate()) < MONTH(@BirthDate)
set @years_old = @years_old -1

if day(getdate()) < day(@BirthDate)
and month(getdate()) = MONTH(@BirthDate)
set @years_old = @years_old -1

else
set @years_old = year(getdate()) - year(@BirthDate)
return @years_old
end
GO
PRINT N'Creating Function [dbo].[fn_gender]...';


GO
CREATE function dbo.fn_gender(@gender1 nvarchar (20))
returns bit
as
begin
declare @Gender_id bit
	set @Gender_id=(select GenderID from gender where @gender1=GenderName)
return @Gender_id
end
GO
PRINT N'Creating Function [dbo].[fn_is_strong_password]...';


GO
CREATE function dbo.fn_is_strong_password (@password1 nvarchar (10),@username nvarchar (10))
returns bit
as
begin
declare @res bit
if ((len(@password1) between 5 and 10)
	and (UPPER(@password1) collate Latin1_General_CS_AS!=@password1) /*בדיקת אות קטנה*/
	/*cs_as = case sensitive accent sensitive*/
	/*latin1 = ascii*/
	and (lower(@password1) collate Latin1_General_CS_AS!=@password1) /*בדיקת אות גדולה*/
	and (@password1 like '%[0-9]%')
	and (@password1 != @username)
	and (@password1 not like '%password%'))
	set @res = 1 -- strong pass
else
	set @res = 0 -- weak pass
return @res
end
GO
PRINT N'Creating Function [dbo].[fn_RandomNum]...';


GO
CREATE function [dbo].[fn_RandomNum](@Lower int, @Upper int)
returns int
as
Begin

DECLARE @Random INT;
if @Upper > @Lower
	SELECT @Random = (@Upper +1- @Lower) * (SELECT * FROM view_GETRANDVALUE) + @Lower
Else
	SELECT @Random = (@Lower +1 - @Upper) * (SELECT * FROM view_GETRANDVALUE) + @Upper
return @Random
end
GO
PRINT N'Creating Function [dbo].[fn_real_email]...';


GO
--checker if email Address is legal
CREATE function dbo.fn_real_email(@Email varchar(30))
returns bit
as
begin
declare @res bit
if (@Email like '%@%')
	set @res = 1 --legal email
else
	set @res = 0 --error email
return @res
end
GO
PRINT N'Creating Function [dbo].[fn_return_bankroll]...';


GO
create function fn_return_bankroll (@userid int)
returns int
as
begin
declare @bankroll int=0
--if exists
--(select 1 from [dbo].[Players] where playerid=@playerid)

    select top 1 @bankroll= sum(bankroll) over(partition by userid order by startplay 
	rows between unbounded preceding and current row) 
  from Transactions
  where userid=@userid
  order by StartPlay desc
  return @bankroll
end
GO
PRINT N'Creating Function [dbo].[FN_support_bring_new_password]...';


GO

CREATE FUNCTION dbo.FN_support_bring_new_password
(
@username nvarchar(10)
)
returns nvarchar(7)
AS
BEGIN
DECLARE @string nvarchar(26)='ABCDEFGHIJKLMNOPQRSTUVWXYZ'
DECLARE @Password nvarchar(7)
DECLARE @first_UPPER_letter nvarchar(1)
DECLARE @second_UPPER_letter nvarchar(1)
DECLARE @first_lower_letter nvarchar(1)
DECLARE @second_lower_letter nvarchar(1)
DECLARE @digits int

SET @first_UPPER_letter=Substring(@string,[dbo].[fn_RandomNum](1,26),1)
SET @second_UPPER_letter=Substring(@string,[dbo].[fn_RandomNum](1,26),1)
SET @first_lower_letter=lower(Substring(@string,[dbo].[fn_RandomNum](1,26),1))
SET @second_lower_letter=lower(Substring(@string,[dbo].[fn_RandomNum](1,26),1))
SET @digits=[dbo].[fn_RandomNum](1,99)

SET @Password=@first_UPPER_letter+@second_UPPER_letter+@first_lower_letter+@second_lower_letter+convert(nvarchar(3),@digits)
RETURN @Password
END
GO
PRINT N'Creating Function [dbo].[fn_username]...';


GO
CREATE function dbo.fn_username (@username1 nvarchar (10))
returns nvarchar (10)
as
begin
	
	DECLARE @userlength int
	SET @userlength=len(@username1)
	while exists (select * from players where Username=@username1)
	BEGIN
		if @userlength>7
		BEGIN
			SET @username1=left(@username1,7)+CONVERT(nvarchar(3),dbo.fn_RandomNum(999,100))
		END
		ELSE
		BEGIN
			SET @username1=left(@username1,@userlength)+CONVERT(nvarchar(3),dbo.fn_RandomNum(999,100)) 
		END
	END

	while not exists (select * from players where Username=@username1)
	begin 
		if @userlength>10
		BEGIN
			SET @username1=left(@username1,10)
		END
		ELSE
		BEGIN
			return @username1
		END
	END
			
return @username1
end
GO
PRINT N'Creating Procedure [dbo].[Call_support]...';


GO
CREATE PROCEDURE Call_support
@username nvarchar(10)
AS
DECLARE @new_password nvarchar(20)
IF not exists (select * from players where Username=@username)
	PRINT 'The user name does not exist please enter a correct user name or register'
ELSE 
	 BEGIN
			SET @new_password=dbo.FN_support_bring_new_password(@username)
			IF  @new_password=@username
			SET @new_password=@new_password+'1'
	 END
	 IF (Select isblocked from players where Username=@username)!=1  
		 BEGIN
			 update players
			 SET CountFailedPassword=0,Password=@new_password
			 where Username=@username
			 PRINT 'You are not block but anyway since you called us, we will give you a new password, your new password is: '+@new_password
		 END
	 ELSE    
		BEGIN
			update players
			SET isblocked=0,Password=@new_password
			where Username=@username
			PRINT ' Your new password is: ' +@new_password
		END
GO
PRINT N'Creating Procedure [dbo].[sp_cash_out]...';


GO

CREATE procedure [dbo].[sp_cash_out] 
				(@userId int = 0,
				@CashOut money = 0 )
as
begin
	declare	@BankRoll money = 0,
	@cust_Address sysname = '' -- varchar(128)

set @BankRoll = 0

select @BankRoll = BankRoll 
				from Transactions
				where userId = @userId
				and Startplay = (select max(startplay) from [transactions] 
								where UserID=@userId)

set @cust_Address = ' '

 select @cust_Address = Adress
				from Players
				where UserNameID = @userId

-----------------------------------------------
if @CashOut > @BankRoll

	begin
		print 'Not enough money in bank'
	end
else
	if @cust_Address  is null
		begin
			print 'No Address'
		end
	else
	begin
		insert into transactions (userid, amount, BankRoll)
		values(@userid,@cashOut,(@BankRoll - @CashOut))

	end
end
GO
PRINT N'Creating Procedure [dbo].[sp_ChangePersonalDetails]...';


GO
Create procedure sp_ChangePersonalDetails
(
@usernameid int,
@username nvarchar (10),
@password1 varchar (20),
@firstname varchar(20),
@lastname varchar(20),
@adress varchar(100),
@countryid int,
@email varchar(30),
@genderid int,
@birthdate date)
as
begin
declare @msg nvarchar(max)=''

INSERT INTO Log(ProcedurName,RunDate)
     VALUES ('sp_ChangePersonalDetails',getdate())

--check if there is any updates
if @password1 = (select Password from Players where usernameid=@usernameid)
And @firstname = (select FirstName from Players where usernameid=@usernameid)
And @lastname = (select LastName from Players where usernameid=@usernameid)
And @adress = (select Adress from Players where usernameid=@usernameid)
And @countryid = (select CountryID from Players where usernameid=@usernameid)
And @email = (select Email from Players where usernameid=@usernameid)
And @genderid = (select Genderid from Players where usernameid=@usernameid)
And @birthdate = (select Birthdate from Players where usernameid=@usernameid)
set @msg= 'pls update your details' 
return
--check if user wants to update details without password
if @password1 = (select Password from Players where usernameid=@usernameid)
begin
UPDATE [dbo].[Players]
   SET [FirstName] = @firstname
      ,[LastName] = @lastname
      ,[Adress] = @adress
      ,[CountryID] = @countryid
      ,[Email] = @email 
      ,[Genderid] = @genderid
      ,[Birthdate] = @birthdate
     
 WHERE usernameid=@usernameid
set @msg='you updated your personal details without changing your password'
end
else
		begin
		--check if  new password was in use in past
		if @password1 in ( select Password from players where usernameid=@usernameid)
		set @msg= 'This password is already in use.
		please choose another password.'

		--check password validation
		else if (select [dbo].[fn_is_strong_password] (@password1,@username ))=0
		set @msg= 'This password is not valid.
		Please Choose differnt passward'
		else
		begin
		UPDATE [dbo].[Players]
			 SET   [Password] = @password1
				  ,[FirstName] = @firstname
				  ,[LastName] = @lastname
				  ,[Adress] = @adress
				  ,[CountryID] = @countryid
				  ,[Email] = @email 
				  ,[GenderID] = @genderid
				  ,[Birthdate] = @birthdate
     
			 WHERE usernameid=@usernameid
set @msg='you update your personal details with changing your password'
		end
		end 
select @msg
end
GO
PRINT N'Creating Procedure [dbo].[sp_deposit]...';


GO

CREATE procedure [dbo].[sp_deposit]
@username varchar(10),
@DepositAmount money
as
begin
declare @p_id int
	set @p_id = (select UserNameID from players where @username=Username)
declare @Bankroll money
	set @Bankroll = (select sum(BankRoll) from [Transactions] where UserID=@p_id)
Declare @Bankroll_after_Deposit money
	set @Bankroll_after_Deposit=@bankroll+@DepositAmount


if not exists(select * from players where @username=Username)
	print 'The username does not exist in the system, please register'

ELSE
	begin
		insert into Transactions(UserId, Startplay,amount,BankRoll)
		values ((select usernameid from players where @username=Username),getdate(),@DepositAmount,@BankRoll)
	end
end
GO
PRINT N'Creating Procedure [dbo].[sp_goto]...';


GO
create procedure sp_goto(@UserNameID int)
as 
begin
select @UserNameID as UNID
end
GO
PRINT N'Creating Procedure [dbo].[sp_InsertTransaction]...';


GO

CREATE procedure sp_InsertTransaction(
@UserID int,@Startplay datetime,@GameID int, @round int, @TransactionType int
,@amount money)
	
	as
begin

INSERT INTO Log(ProcedurName,RunDate)
     VALUES ('sp_insertGameTransaction',getdate())


	if @TransactionType in (1,3,5)
	begin
	INSERT INTO [dbo].[Transactions]
	([UserID],[StartPlay],[GameId],[Round],[TransactionTypeID],[Amount])
		 VALUES
 (@UserID ,getdate() ,@GameID , @round , @TransactionType ,@amount)
 end
	else
begin
	INSERT INTO [dbo].[Transactions]
	([UserID],[StartPlay],[GameId],[Round],[TransactionTypeID],[Amount])
		 VALUES
	 (@UserID ,getdate() ,@GameID , @round , @TransactionType ,-@amount)
	end
end
GO
PRINT N'Creating Procedure [dbo].[sp_login]...';


GO

create proc sp_login( @user varchar (100), @pass varchar(100), @OutPutParam int output)
as
begin
	if exists (select 1 from Players
	where UserName = @user and Password =@pass and isblocked=0)

begin 
	update players  set CountFailedPassword = 0
	set @OutPutParam=1 --ok sucssess
end
else

	if exists (select 1 from Players where UserName = @user)
begin
	declare @count int =0 

	select @count = CountFailedPassword from players
	where UserName = @user

	if (@count >= (select [value] from configuration 
	where  [description] = 'max_failed'))

begin
update Players set isblocked = 1
set  @OutPutParam=2--failed 5 times
end

else
update Players set CountFailedPassword +=1
end
 set  @OutPutParam=0 --'deny'
 return
end
GO
PRINT N'Creating Procedure [dbo].[sp_logout]...';


GO



create procedure sp_logout(@UserNameID int)
as
begin
INSERT INTO Log(ProcedurName,RunDate)
     VALUES ('sp_logout',getdate())

update [dbo].[Players]
set [LoginIndicator]=0 where UserNameID = @UserNameID
end
GO
PRINT N'Creating Procedure [dbo].[sp_NoLogins]...';


GO
Create procedure  sp_NoLogins
as
begin
INSERT INTO Log(ProcedurName,RunDate)
     VALUES ('NoLogins',getdate())

if datediff (minute,(select top 1 RunDate from log 
where [ProcedurName]='sp_login' order by RunDate desc),getdate())>=(select [value] from configuration 
where  [description] = 'nologintime')

print 'email was sent to System Adminstrator '

end
GO
PRINT N'Creating Procedure [dbo].[sp_NoOfUseres]...';


GO
create procedure sp_NoOfUseres 
as 
begin
if 
(select count(usernameID) from players where LogInIndicator=1)>(select value from Configuration where Description='NumberOfConnection')
print 'send e-mail to sys admin'
else 
print 'OK'
end

insert into configuration ([description],[value])
values ('NumberOfConnection',100)--nn
GO
PRINT N'Creating Procedure [dbo].[SP_Registration]...';


GO

CREATE PROCEDURE [dbo].[SP_Registration]
@username nvarchar(10),
@password varchar(20),
@firstname nvarchar(20),
@lastname varchar(20),
@Address varchar(100),
@country varchar(30),
@EmailAddress varchar(30),
@Gender varchar(6),
@BirthDate date 

AS
if exists (select * from dbo.players where UserName=@username)
	begin
		set @username = ( select dbo.fn_username(@username))
		print 'The user name that you chose has already exist,you may choose user name: '+ @username
	end
else
	begin
	if ( dbo.fn_is_strong_password(@password,@username) = 0)
		print 'You entered weak password,please enter strong password. A password must contain at least 5 characters and a maximum of 10 characters and also at least one large letter, one small letter, and one number'
	else
		begin
if not exists (select CountryName from countries where CountryName=@country)
	print 'Please enter a valid country'
else
	if ( dbo.fn_real_email(@EmailAddress)=0)
		print 'You entered Invalid email, a valid email contains the character @'
	else
	if exists (select * from dbo.players where Email=@EmailAddress) 
		print 'The email that you entered is already exists in the system'
		else
		begin
			if(dbo.fn_18_years_old(@BirthDate)<18)
			print 'You can enter from the age of 18 and up'
			else
				begin
					insert into players ([UserName],[Password],[FirstName],[LastName],[Adress],
					[CountryId],[EMail],[GenderID],[BirthDate],[isblocked],[CountFailedPassword],[LoginIndicator])

					values (@username,@password,@firstname,@lastname,@Address,@country,
					@EmailAddress,dbo.fn_gender(@Gender),@BirthDate,0,0,1)

					insert into transactions (userid, startplay, GameId, round,TransactionTypeID , amount, bankroll)
					values ((select UserNameID from players where @username=Username),getdate(),4,0,5,10,10)
							end
			end
		end
	end
GO
PRINT N'Creating Procedure [dbo].[sp_slot_machine]...';


GO

CREATE procedure [dbo].[sp_slot_machine] 
--returns nvarchar (1)
as
begin
declare @game bit
declare @msg nvarchar (max)='your cards are: '
declare @a nvarchar (1)
	set @a = (select * from view_SLOTMACHINE)
declare @b nvarchar (1)
	set @b = (select * from view_SLOTMACHINE)
declare @c nvarchar (1)
	set @c = (select * from view_SLOTMACHINE)
--print @a 
--print @b
--print @c


if(@a=@b and @b=@c)
	set @game = '1'--win
else
	set @game = '0'--lose

print @game
print @a + @b + @c
--print @b
--print @c
 

end
GO
PRINT N'Creating Procedure [dbo].[sp_BlackJackGame]...';


GO
CREATE procedure sp_BlackJackGame( @usernameid int,@Amount money,@PlayerCardsNum int,@randomdate bit =null)
as
begin
INSERT INTO Log(ProcedurName,RunDate)
     VALUES ('sp_BlackJackGame',getdate())

declare @count int =0
declare @cardvalue int=0
declare @card int =0
declare @SumCardsPlayer int =0
declare @SumCardsDealer int =0
declare @HaveAce int =0
declare @msg nvarchar (max)='your cards are: '
declare @GameResultPlayer int

declare @bankroll int =(select [dbo].[fn_return_bankroll](@usernameid))
if @Amount>@bankroll
begin
set @msg+='your have:'
+cast(@bankroll as nvarchar)+'in your account, please enter smaller amount'
select @msg 
return
end
--get player cards
while @count<@PlayerCardsNum
begin
set @card=(SELECT TOP 1 id FROM cardspkg where id in 
			(SELECT id from [dbo].[CardsPkg] where [IsAvailable]=1
			)order by newid()) /*רנדומלי*/
set @SumCardsPlayer += (select cardvalue from [dbo].[CardsPkg] where id=@card)
if (select CardSymbol from [dbo].[CardsPkg] where id=@card) =1
set @HaveAce+=1
update [dbo].[CardsPkg] set [IsAvailable]=0 where id=@card
set @cardvalue =(select cardvalue from [dbo].[CardsPkg] where id=@card)
set @msg+=CAST( @cardvalue as char(3)) +','
--print @SumCardsPlayer
set @count+=1
end

--check if player cards are equal or biger then 21
if @SumCardsPlayer>=21
	begin
		
		
		--check if have Ace, and set the value
		if @HaveAce=4
		begin
	
		set @SumCardsPlayer-=30
		set @msg+= ' you had 4 Ace cards. the best value of all is 1' 
		end
		else if @HaveAce=3
		begin
	
		set @SumCardsPlayer-=20
		set @msg+= ' you had 3 Ace cards. the best value of all is 1' 
		end
		else if @HaveAce=2
			begin	
		
				if (@SumCardsPlayer-10)>21
				begin
				
				set @SumCardsPlayer-=20
				set @msg+= ' you had 2 Ace cards. the best value for both is 1'
				end
				else 
				begin
			
				set @SumCardsPlayer-=10
				set @msg+= ' you had 2 Ace cards. the best values are 1 and 11'
				end
			end
			else if @HaveAce=1
			begin
			
			 set @SumCardsPlayer-=10
			 set @msg+= ' you had an Ace cards. the best value  is 1'
			 end
		else
		begin
		
		set @GameResultPlayer=5
		set @msg+= ' you have more then 21 points, game over'
		select @msg
		update [dbo].[CardsPkg] set [IsAvailable]=1 where [IsAvailable]=0
		exec dbo.sp_InsertTransaction @usernameID,2,@Amount,@GameResultPlayer,@randomdate
		return
		--print 'the sum card of player was ' +cast(@SumCardsPlayer as nvarchar)
		--print 'the sum card of Dealer was ' +cast(@SumCardsDealer as nvarchar)
		end
	
	end
	--if @GameResultPlayer=4
	--print ' the gamer result is: win!!!!'
	--else 
	--print 'you lose the game'
	--update [dbo].[CardsPkg] set [IsAvailable]=1
	--return
	--end
--else 
begin

--dealer takes cards till win/lose
while @SumCardsDealer<@SumCardsPlayer and @SumCardsDealer<21
		begin
		
			set @card=(SELECT TOP 1 id FROM cardspkg where id in 
			(SELECT id from [dbo].[CardsPkg] where [IsAvailable]=1
			)order by newid())
			set @SumCardsDealer+=(select cardvalue from cardspkg where id=@card)
			update [dbo].[CardsPkg] set [IsAvailable]=0 where id=@card
		end

if @SumCardsDealer>=21
begin

set @GameResultPlayer=4
end
else
begin

set @GameResultPlayer=5
end

end

set @msg+= ' the sum card of player was ' +cast(@SumCardsPlayer as nvarchar)
+ ' the sum card of Dealer was ' +cast(@SumCardsDealer as nvarchar) 
if @GameResultPlayer=4
begin

set @msg+=  ' the gamer result is: win!!!!' 
end
else 
begin
set @msg+= ' you lose the game' 

end

update [dbo].[CardsPkg] set [IsAvailable]=1 where [IsAvailable]=0


exec dbo.sp_InsertTransaction @usernameID,2,@Amount,@GameResultPlayer,@randomdate
select @msg
end

---exec sp_BlackJackGame 13,300,3
GO
PRINT N'Creating Procedure [dbo].[sp_CheckDepoistInOneDay]...';


GO

CREATE procedure [dbo].[sp_CheckDepoistInOneDay] 
as begin
INSERT INTO Log(ProcedurName,RunDate)
     VALUES ('CheckDepoistInOneDay',getdate())


	 
DECLARE c CURSOR FOR 
SELECT distinct UserID from Transactions where datediff(HOUR,Startplay,GETDATE())<48 
declare @UserID int  
open c
FETCH NEXT FROM c INTO @UserID

WHILE @@FETCH_STATUS = 0  
BEGIN  
     
	 if(select sum(Amount) as mysum from Transactions where datediff(HOUR,Startplay,GETDATE())<(select [value] from configuration 
		where  [description] = 'TimeToEarnBonus')  and  UserId =@userid) > (select value from Configuration where Description='AmountDepositedInOneDay')
	 begin
	 declare @amount int=(select [Value] from [Configuration] where Description='ExtraDepositBonusAmount')
	 exec sp_insertTransaction @UserID ,4,@amount , 3
	 end

      FETCH NEXT FROM c INTO @UserID 
	  
END 

CLOSE c 
DEALLOCATE c

end
GO
PRINT N'Creating Procedure [dbo].[sp_CheckNotActive]...';


GO

create procedure [sp_CheckNotActive] 
as 
begin
INSERT INTO Log(ProcedurName,RunDate) VALUES ('CheckNotActive',getdate())  

DECLARE c CURSOR FOR SELECT UserNameID FROM players where LoginIndicator=1  
declare @UserNameID int  
open c
FETCH NEXT FROM c INTO @UserNameID

WHILE @@FETCH_STATUS = 0  
BEGIN  
     
	 if datediff(MINUTE,(select top 1 ValidFrom 
						from Players
						where UserNameID = @UserNameID order by ValidFrom desc),getdate())>5
	 begin
	 print @UserNameID
	 exec sp_logout @UserNameID
	 end
      FETCH NEXT FROM c INTO @UserNameID
	  
END 

CLOSE c 
DEALLOCATE c

end
GO
PRINT N'Creating Procedure [dbo].[SP_Horse_race]...';


GO

-- Horse Race
CREATE PROCEDURE SP_Horse_race (@usernameid int,@Amount money,@date datetime, @HorseNumber tinyint)
AS

DECLARE
	@Horse1Position			AS TINYINT			= 0 ,
	@Horse2Position			AS TINYINT			= 0 ,
	@Horse3Position			AS TINYINT			= 0 ,
	@Horse4Position			AS TINYINT			= 0 ,
	@Horse5Position			AS TINYINT			= 0 ,
	@MaxHorsePosition		AS TINYINT			= 0 ,
	@MaxTrackPosition		AS TINYINT			= 5 ,
	@MaxStepsPerIteration	AS TINYINT			= 3 ,
	@Winner					AS TINYINT ,
	@LineToPrint			AS NVARCHAR(MAX),
	@msg nvarchar (max)='you have',
	@game int = 0;

declare @bankroll int =(select [dbo].[fn_return_bankroll](@usernameid))
if @Amount>@bankroll
begin
set @msg+='you have:'
+cast(@bankroll as nvarchar)+'in your account, please enter smaller amount'
select @msg 
return
end

WHILE
	1 = 1
BEGIN

	SET @LineToPrint = REPLICATE ('.' , @Horse1Position) + '1' + REPLICATE ('.' , @MaxTrackPosition - @Horse1Position);
	RAISERROR (@LineToPrint , 0 , 1) WITH NOWAIT;

	SET @LineToPrint = REPLICATE ('.' , @Horse2Position) + '2' + REPLICATE ('.' , @MaxTrackPosition - @Horse2Position);
	RAISERROR (@LineToPrint , 0 , 1) WITH NOWAIT;

	SET @LineToPrint = REPLICATE ('.' , @Horse3Position) + '3' + REPLICATE ('.' , @MaxTrackPosition - @Horse3Position);
	RAISERROR (@LineToPrint , 0 , 1) WITH NOWAIT;

	SET @LineToPrint = REPLICATE ('.' , @Horse4Position) + '4' + REPLICATE ('.' , @MaxTrackPosition - @Horse4Position);
	RAISERROR (@LineToPrint , 0 , 1) WITH NOWAIT;

	SET @LineToPrint = REPLICATE ('.' , @Horse5Position) + '5' + REPLICATE ('.' , @MaxTrackPosition - @Horse5Position);
	RAISERROR (@LineToPrint , 0 , 1) WITH NOWAIT;

	RAISERROR ('' , 0 , 1) WITH NOWAIT;

	IF
		@MaxHorsePosition = @MaxTrackPosition
	BEGIN

		BREAK;
		END;

	SET @Horse1Position += CAST ((RAND () * (@MaxStepsPerIteration + 1)) AS TINYINT) % (@MaxStepsPerIteration + 1);

	IF
		@Horse1Position > @MaxTrackPosition
	BEGIN
		SET @Horse1Position = @MaxTrackPosition;
			END;
		IF
		@Horse1Position > @MaxHorsePosition
	BEGIN
			SET @MaxHorsePosition = @Horse1Position;
		SET @Winner = 1;
			END;
	SET @Horse2Position += CAST ((RAND () * (@MaxStepsPerIteration + 1)) AS TINYINT) % (@MaxStepsPerIteration + 1);
		IF
		@Horse2Position > @MaxTrackPosition
	BEGIN

		SET @Horse2Position = @MaxTrackPosition;

	END;

	IF
		@Horse2Position > @MaxHorsePosition
	BEGIN
		SET @MaxHorsePosition = @Horse2Position;
		SET @Winner = 2;

	END;

	SET @Horse3Position += CAST ((RAND () * (@MaxStepsPerIteration + 1)) AS TINYINT) % (@MaxStepsPerIteration + 1);
	IF
		@Horse3Position > @MaxTrackPosition
	BEGIN
		SET @Horse3Position = @MaxTrackPosition;
	END;
	IF
		@Horse3Position > @MaxHorsePosition
	BEGIN
		SET @MaxHorsePosition = @Horse3Position;
		SET @Winner = 3;

	END;

	SET @Horse4Position += CAST ((RAND () * (@MaxStepsPerIteration + 1)) AS TINYINT) % (@MaxStepsPerIteration + 1);

	IF
		@Horse4Position > @MaxTrackPosition
	BEGIN

		SET @Horse4Position = @MaxTrackPosition;

	END;

	IF
		@Horse4Position > @MaxHorsePosition
	BEGIN

		SET @MaxHorsePosition = @Horse4Position;
		SET @Winner = 4;

	END;

	SET @Horse5Position += CAST ((RAND () * (@MaxStepsPerIteration + 1)) AS TINYINT) % (@MaxStepsPerIteration + 1);

	IF
		@Horse5Position > @MaxTrackPosition
	BEGIN

		SET @Horse5Position = @MaxTrackPosition;

	END;

	IF
		@Horse5Position > @MaxHorsePosition
	BEGIN

		SET @MaxHorsePosition = @Horse5Position;
		SET @Winner = 5;

	END;

--	WAITFOR DELAY '00:00:03';

END;
if @HorseNumber = @Winner

	set @game = 1--win
else
	set @game = 0--lose

exec dbo.sp_InsertTransaction @usernameID,@date,3,3,@Amount

SET @LineToPrint = 'The winner is horse #' + CAST (@Winner AS NVARCHAR(MAX)) + '!';
PRINT @LineToPrint;
GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[Players] WITH CHECK CHECK CONSTRAINT [FK_Players_Countries];

ALTER TABLE [dbo].[Players] WITH CHECK CHECK CONSTRAINT [FK_Players_Gender];

ALTER TABLE [dbo].[Transactions] WITH CHECK CHECK CONSTRAINT [FK_Transactions_Games];

ALTER TABLE [dbo].[Transactions] WITH CHECK CHECK CONSTRAINT [FK_Transactions_Players];

ALTER TABLE [dbo].[Transactions] WITH CHECK CHECK CONSTRAINT [FK_Transactions_TransactionType];


GO
PRINT N'Update complete.';


GO
